services:
  nginx:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - auth-service

  auth-service:
    build:
      context: auth-service
      dockerfile: Dockerfile
    expose:
      - "8000"
    restart: unless-stopped